[[action]]

return="url"

[action.target]
key="url"
type="string"
value="https://www.gufengmh8.com/manhua/woweicangsheng/1163707.html"

[action.operation]
key="html"
type="download"
value=""

[action.before]
[action.before.option]
cookie=""
proxy=""
[action.before.replace]
target="url"
from="www\\.gufengmh8"
#to="m.gufengmh8"
#
[action.after]
[action.after.transform]
target="html"
from="gbk"
to="utf8"
[action.after.replace]
target="html"
from="<img{^>}+src=\"({^\"}+)\"{^>}+data-original=\"({^\"}+)\">"
to="<img src=\"$1\" data-original=\"$2\">"



[[action]]
return=""

[action.target]
key="url"
type="temp"
value=""

[action.operation]
key="code"
type="regex\\.get"
value="://\\w+.(\\w+).\\w+"

[[action]]
return=""
[action.target]
key="html"
type="temp"
value=""
[action.operation]
key="dom"
type="dom_parser"
value=""


[[action]]
return="title"
[action.target]
key="dom"
type="temp"
value=""
[action.operation]
key="title"
type="find"
value=".chapter-view h2"


[[action]]
return="number"
[action.target]
key="html"
type="temp"
value=""
[action.operation]
key="number"
type="regex\\.get"
value="comic.(\\w+)"

[[action]]
return="chapter"
[action.target]
key="url"
type="temp"
value=""
[action.operation]
key="chapter"
type="regex\\.get"
value="(\\w+)\\.html"

[[action]]
return=""
[action.target]
key="html"
type="temp"
value=""
[action.operation]
key="imagePath"
type="regex\\.get"
value="var chapterPath\\s?=\\s?\"([^\"]+)\""


[[action]]
return=""
[action.target]
key="html"
type="temp"
value=""
[action.operation]
key="imgsStr"
type="regex\\.get"
value="var chapterImages\\s?=\\s?\\[([^\\]]+)\\]"
[action.after]
[action.after.replace]
target="imgsStr"
from="\""
to=""

[[action]]
return="imgs"
[action.target]
key="imgsStr"
type="temp"
value=""
[action.operation]
key="imgs"
type="strings.Split"
value=","
[action.after]
[action.after.filter]
target="imgs"
value=""
